config/routes.rb
Rails.application.routes.draw do
  resources :products
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photos.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  #photo belongs to product
  belongs_to :photo

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :codigo, :azul, :blanco, :nude, :negro, :gris, :verde, :S, :M, :L, :XL, :sexo, :precio, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rv10 Catalogo Online</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title><%= meta_title %></title>

 <!--FAVICON-->
<%= favicon_link_tag asset_path('logo-1.png') %>

 <!-- META TAGS -->
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />


<!--OTHER LINKS-->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>

    <%= yield %>
    <script type="text/javascript">
    (function () {
        var options = {
            whatsapp: "+59178012323", // WhatsApp number
            call_to_action: "¡Envíenos un mensaje!", // Call to action
            position: "right", // Position may be 'right' or 'left'
        };
        var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
        s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();
</script>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Francois+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5cf079077feea60012093eb2&product=sticky-share-buttons' async='async'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<!-- /WhatsHelp.io widget -->


</br>
</br>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :azul %>
    <%= form.check_box :azul %>
  </div>

  <div class="field">
    <%= form.label :blanco %>
    <%= form.check_box :blanco %>
  </div>

  <div class="field">
    <%= form.label :nude %>
    <%= form.check_box :nude %>
  </div>

  <div class="field">
    <%= form.label :negro %>
    <%= form.check_box :negro %>
  </div>

  <div class="field">
    <%= form.label :gris %>
    <%= form.check_box :gris %>
  </div>

  <div class="field">
    <%= form.label :verde %>
    <%= form.check_box :verde %>
  </div>

  <div class="field">
    <%= form.label :S %>
    <%= form.check_box :S %>
  </div>

  <div class="field">
    <%= form.label :M %>
    <%= form.check_box :M %>
  </div>

  <div class="field">
    <%= form.label :L %>
    <%= form.check_box :L %>
  </div>

  <div class="field">
    <%= form.label :XL %>
    <%= form.check_box :XL %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @product.codigo %>
</p>

<p>
  <strong>Azul:</strong>
  <%= @product.azul %>
</p>

<p>
  <strong>Blanco:</strong>
  <%= @product.blanco %>
</p>

<p>
  <strong>Nude:</strong>
  <%= @product.nude %>
</p>

<p>
  <strong>Negro:</strong>
  <%= @product.negro %>
</p>

<p>
  <strong>Gris:</strong>
  <%= @product.gris %>
</p>

<p>
  <strong>Verde:</strong>
  <%= @product.verde %>
</p>

<p>
  <strong>S:</strong>
  <%= @product.S %>
</p>

<p>
  <strong>M:</strong>
  <%= @product.M %>
</p>

<p>
  <strong>L:</strong>
  <%= @product.L %>
</p>

<p>
  <strong>Xl:</strong>
  <%= @product.XL %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @product.sexo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.precio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @product.descripcion %>
</p>



<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2" style="
    color: darkred !important;
"><%= @product.name %></h1></h1>


      <ul class="pv1">
        <% if @product.azul? %>
        <li class="inline-block pr3"><%= @product.azul %></li>
        <% end %>

        <li class="inline-block pr3"><%= @product.sexo %></li>

        <% if @product.S? %>
        <li class="inline-block pr3"><%= @product.s %></li>
        <% end %>
      </ul>


      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4"><%= @product.name %></h3>


      </br>
      <div class="feature-image">
      <%= cl_image_tag @product.photo%>
    </div>


 <h3 class="subtitle is-4"></h3>
      <%= @product.descripcion %>

      <h3 class="subtitle is-4 pt5">Descripcion</h3>

      <table class="table is-narrow">
        <% if @product.S%>
        <tr>
          <td class="has-text-weight-bold">Gender</td>
          <td><%= @product.sexo %></td>
        </tr>
        <% end %>

        <% if @product.azul %>
          <tr>
            <td class="has-text-weight-bold">azul:</td>
            <td><%= @product.azul %></td>
             <td><%= @product.gris %></td>
          </tr>
        <% end %>

        <% if @product.S %>
          <tr>
            <td class="has-text-weight-bold">S:</td>
            <td><%= @product.S %></td>
            <td class="has-text-weight-bold">M:</td>
            <td><%= @product.M %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Price:</td>
          <td>Bs.<%=@product.precio %></td>
        </tr>
      </table>
    </div>
    </div>



    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered" style="
    color: darkred !important;
">Bs. <%=(@product.precio) %></h4>

      </div>
      </div>
    </div>
  </div>

</section>